# Generated by Django 5.1.7 on 2025-03-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_company_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='vkn',
        ),
    ]
