# Generated by Django 5.1.7 on 2025-03-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_company_vkn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user_id',
            new_name='user',
        ),
    ]
