# Generated by Django 5.1.7 on 2025-03-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_id_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], max_length=200)),
            ],
            options={
                'db_table': 'types',
            },
        ),
    ]
